language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

# Using Testbench you can test for different Laravel versions.
# The settings below test on each PHP version Laravel 5.4 and 5.5.
env:
  - TESTBENCH_VERSION=3.*
  - TESTBENCH_VERSION=4.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
